# =========================================================
# RENDER POSTGRESQL DATABASE
# =========================================================

spring.datasource.url=jdbc:postgresql://dpg-da59k2jm8hqs73bucdm0-a.singapore-postgres.render.com:5432/aktech_overseas?sslmode=require
spring.datasource.username=aktech_user
spring.datasource.password=LSGAzJkpbc3tMRcR4zngKkEpSKXag4dT
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# =========================================================
# SERVER
# =========================================================

server.port=${PORT:8080}