
spring.datasource.url=jdbc:postgresql://localhost:5432/aktech_overseas
spring.datasource.username=postgres
spring.datasource.password=aktech123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# =========================================================
# JWT
# =========================================================

jwt.secret=AKTechOverseasJWTSecretKey2026ForSecureAuthenticationSystem

# =========================================================
# ADMIN EMAIL
# =========================================================

app.admin.email=YOUR_ADMIN_EMAIL@gmail.com

# =========================================================
# EMAIL
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dakudrs@gmail.com
spring.mail.password=przdttmwhvzxsnzq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================================================
# SERVER
# =========================================================

server.port=8080
