spring.datasource.url=jdbc:postgresql://localhost:5432/aktech_overseas
spring.datasource.username=postgres
spring.datasource.password=aktech123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update